#!/bin/bash

mod_mem () {
	#free --mebi | sed -n '2{p;q}' | awk '{printf (" %2.2f/%2.2fGB\n", ( $3 / 1024), ($2 / 1024))}'
	free --mebi | sed -n '2{p;q}' | awk '{printf (" %2.2f GB", ( $3 / 1024))}'
}

