#!/bin/bash

# Requires amixer from the alsa-utils package

mod_vol_amixer () {
  # Customizable configuration constants
  local -r DEFAULT_PRE_LOW=' '
  local -r DEFAULT_PRE_HI=' '
  local -r DEFAULT_PRE_MUTE=' '
  local -r DEFAULT_SUF='%'

  local -r pre_low="${1-${DEFAULT_PRE_LOW}}"
  local -r pre_hi="${2-${DEFAULT_PRE_HI}}"
  local -r pre_mute="${3-${DEFAULT_PRE_MUTE}}"
  local -r suf="${4-${DEFAULT_SUF}}"

  local pre vol

  vol="$(pamixer --get-volume)"
  [ -z "$vol" ] && vol="20"
  stat="$(pamixer --get-mute)"

if [[ "${vol}" -lt 50 ]]; then pre="${pre_low}";
else pre="${pre_hi}"; fi
  printf '%b%3d%b' "${pre}" "${vol}" "${suf}"
}

